# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: bookstore
services:
- name: books-api
  project: Books/Bookstore.Api/Bookstore.Api.csproj
- name: books-db
  image: postgres:11.19-alpine
  env:
    - name: POSTGRES_USER
      value: bookstore-dbuser
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_DB
      value: bookstore-db
  bindings:
    - port: 54320
      containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: bookstore-broker
  image: rabbitmq:3.11-management-alpine
  bindings:
    - name: management
      protocol: http
      port: 15672
      containerPort: 15672
    - name: protocol
      port: 5672
      containerPort: 5672
      connectionString: ${host}
- name: publishers-api
  project: Publishers/Publisher.Api/Publisher.Api.csproj
- name: publishers-db
  image: postgres:11.19-alpine
  env:
    - name: POSTGRES_USER
      value: publishers-dbuser
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_DB
      value: publishers-db
  bindings:
    - port: 54321
      containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};